<?php $developerHelper = $this->helper('PeterBrain\Core\Helper\Developer'); ?>

<style>
table, th, td {
  padding: 5px 0.5em;
}
</style>
<table>
  <tbody>
    <tr>
      <td>Extension developer:</td>
      <td><a href="https://github.com/PeterBrain" title="Link to Github profile">PeterBrain</a></td>
      <td><a href="https://paypal.me/peterbrain?country.x=AT&locale.x=de_DE" title="Buy me a coffe">Buy me a coffee</a></td>
    </tr>
    <tr>
      <td>Module version:</td>
      <td><?php /* @noEscape */ echo $developerHelper->getModuleVersion(); ?></td>
      <td></td>
    </tr>
  </tbody>
</table>
